<?php
	echo "code";
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');	
	$helper = $this->helper('\Mconnect\Iconlib\Helper\Data');	
	$random=$helper->getConfig('mconnect_iconlib/icon_image_display_setting/display_icon_randomly_enabled');	
	$limit =$helper->getConfig('mconnect_iconlib/general/associationlimit');
		
		$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$storeid[]=0;
	$storeid[]=$storeManager->getStore()->getStoreId();
	$product_id = $product->getId();

	$iconsLib_id = [];
	// echo "<pre>";
	// print_r($storeid);
	// die(__FILE__);	
	
	$iconImageColle = $this->getIconImageColle();	
	$iconImageColle->addFieldToSelect('*')->addFieldToFilter("product_id", ['eq' =>$product_id ]);
	$iconImageColle->addFieldToFilter('store_id', ['in' => $storeid]);
	foreach ($iconImageColle as $iconImg)
	{		
		$iconsLib_id[] = $iconImg->getData('selected_icon');
	
	}
	

	$iconLibColle = $this->getIconlibColle();	
	$iconLibColle->addFieldToSelect('*');
	$iconLibColle->addFieldToFilter('id', ['in' => $iconsLib_id]);	
	$iconLibColle->addFieldToFilter('status', 1);
	
	
	if($random)
	{
		$iconLibColle->getSelect($random)->orderRand();
	}
	else
	{
		$iconLibColle->setOrder('id','DESC');
	}
	
	$iconLibColle->setPageSize($limit);
	
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$mediaurl= $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()
				->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
	
	$isAdminStyle = $helper->getConfig('mconnect_iconlib/icon_image_display_setting/enable_display');
	$isModuleActive = $helper->getConfig('mconnect_iconlib/general/active');			
	$border=$helper->getConfig('mconnect_iconlib/icon_image_display_setting/enable_border');
	$width=$helper->getConfig('mconnect_iconlib/icon_image_display_setting/icon_image_width');
	$height=$helper->getConfig('mconnect_iconlib/icon_image_display_setting/icon_image_height');
	$width= $width .'px'; 
	$height= $height .'px';
	
	foreach ($iconLibColle as $item)
		{
			$icon_id = $item['id'];
			
			$img = $mediaurl . $item['icon_image'];
			
			

			if($item['icon_image'])
			{
				if($isModuleActive)
				{
					if($isAdminStyle)
					{
					?>
						<img  style="width: <?php echo $width; ?>;height: <?php echo $height; ?>;
					<?php 
						if($border)
						{
							echo 'border: 1px solid #ccc;';
						}
						?>"src='<?php echo $img ?>'/> <?php
					}
					else  
					{ 
						?>
						<img src='<?php echo $img ?>'/>
						<?php
					} 
				} 
			} 
		}
?>