<?php $imageCollection = $block->getIconlibColle(); ?>
<?php  
	$width = 100;
	$height = 100;
    $isAdminStyle = $block->getConfig('mconnect_iconlib/icon_image_display_setting/enable_display');
	$isModuleActive = $block->getConfig('mconnect_iconlib/general/active');			
	$border=$block->getConfig('mconnect_iconlib/icon_image_display_setting/enable_border');
	$widthNew = $block->getConfig('mconnect_iconlib/icon_image_display_setting/icon_image_width');
	$heightNew = $block->getConfig('mconnect_iconlib/icon_image_display_setting/icon_image_height');
	if($widthNew){
		$width = $widthNew;
	}
	if($heightNew){
		$height = $heightNew;
	}
	$width= $width .'px'; 
	$height= $height .'px';
	?>
<?php if($imageCollection->getSize()):?>
	<ul class="product-icon-pdp">
		<?php foreach ($imageCollection as $item):?>
			<?php $icon_id = $item['id']; ?>
				<li>
					<?php $icon_id = $item->getId();
					$img = $block->getMediaUrl($item->getIconImage());
					if($item['icon_image']) :
						if($isModuleActive):
							if($isAdminStyle):?>
								<img style="width: <?php echo $width; ?>;height: <?php echo $height; ?>;
							<?php if($border):
									echo 'border: 1px solid #ccc;';
								endif;
								?>"src='<?php echo $img ?>'/> 
							<?php else: ?>
								<img src='<?php echo $img ?>'/>
							<?php endif;?>
						<?php endif;?> 
					<?php endif;?>
				</li>
		<?php endforeach;?>
	</ul>
<?php endif;?>