<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $viewModel = $this->helper('Elsnertech\ProductCustomization\Helper\Data'); ?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <?php if($viewModel->getAttributeOpetion($_product->getId(),"profession_type")=="B2B"): ?>
        <?php if($viewModel->getCurrentCustomeType()!="Salon"): ?>
            <a href="<?= $block->geturl('customer/account/create') ?>" class="professional-search">
                <p class="professional-login"><?= __("Professional Use Only") ?></p>
            </a>
        <?php else: ?>
            <div class="box-tocart">
                <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()) :?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                        <div class="control">
                            <input type="number"
                                name="qty"
                                id="qty"
                                min="0"
                                value="<?= $block->getProductDefaultQty() * 1 ?>"
                                title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                class="input-text qty"
                                data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                />
                                    <div class="qty-ctl">
                                        <button title="decrease" onclick="changeQty(0); return false;" class="decrease-qty"><i class="fa fa-caret-down" aria-hidden="true"></i></button>
                                        <button title="increase" onclick="changeQty(1); return false;" class="increase-qty"><i class="fa fa-caret-up" aria-hidden="true"></i></button>
                                    </div>
                        </div>
                        <?= $this->getLayout()->createBlock('Magento\Catalog\Pricing\Render',
                            "product.price.final.clone",
                            [
                                'data' => [
                                    'price_render' => 'product.price.render.default',
                                    'price_type_code' => 'final_price',
                                    'zone' => 'item_view'
                                ]
                            ]
                        )->toHtml(); ?>
                    </div>
                    <?php endif; ?>
                    <div class="actions">
                        <button type="submit"
                                title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                                class="action primary tocart"
                                id="product-addtocart-button" disabled>
                            <span><?= $block->escapeHtml($buttonTitle) ?></span>
                        </button>
                        <?= $block->getChildHtml('', true) ?>
                        <a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><span><?php echo __('Add to Loves'); ?></span></a>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    <?php else: ?>
        <div class="box-tocart">
                <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()) :?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                        <div class="control">
                            <input type="number"
                                name="qty"
                                id="qty"
                                min="0"
                                value="<?= $block->getProductDefaultQty() * 1 ?>"
                                title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                class="input-text qty"
                                data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                />
                                    <div class="qty-ctl">
                                        <button title="decrease" onclick="changeQty(0); return false;" class="decrease-qty"><i class="fa fa-caret-down" aria-hidden="true"></i></button>
                                        <button title="increase" onclick="changeQty(1); return false;" class="increase-qty"><i class="fa fa-caret-up" aria-hidden="true"></i></button>
                                    </div>
                        </div>
                        <?= $this->getLayout()->createBlock('Magento\Catalog\Pricing\Render',
                            "product.price.final.clone",
                            [
                                'data' => [
                                    'price_render' => 'product.price.render.default',
                                    'price_type_code' => 'final_price',
                                    'zone' => 'item_view'
                                ]
                            ]
                        )->toHtml(); ?>
                    </div>
                    <?php endif; ?>
                    <div class="actions">
                        <button type="submit"
                                title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                                class="action primary tocart"
                                id="product-addtocart-button" disabled>
                            <span><?= $block->escapeHtml($buttonTitle) ?></span>
                        </button>
                        <?= $block->getChildHtml('', true) ?>
                        <a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><span><?php echo __('Add to Loves'); ?></span></a>
                    </div>
                </div>
            </div>
            <?php endif; ?>
    <?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script>
function changeQty(increase) {
    var elementQty = document.getElementsByName("qty")[0];
    var qty = parseInt(elementQty.value);
    if (!isNaN(qty)) {
        qty = increase ? qty + 1 : (qty > 1 ? qty - 1 : 1);
        elementQty.value = qty;
    }
}
</script>