<?php
use Magento\Framework\App\Action\Action;

?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$gtmHelper = $this->helper('WeltPixel\GoogleTagManager\Helper\Data');
$elsnerhelper = $this->helper('Elsnertech\ProductCustomization\Helper\Data');
$groupType = $elsnerhelper->getCurrentCustomeType();
$currentCountry = $elsnerhelper->getCountryName();
$ProfessionalText = $elsnerhelper->getProfessionalText();
if ($currentCountry=="United States") {
    $currentCountry = "US";
} 
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php foreach ($_productCollection as $_product): ?>
                <?php $productCountry = $elsnerhelper->getAttributeOpetion($_product->getId(),"country") ?>
                    <?php if($currentCountry==$productCountry): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                        <div class="product-item-info quick-look" data-container="product-grid">
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <a data-wpproductlabel="1" data-product-id="<?php echo $_product->getId() ?>"
                                <?php if ($gtmHelper->isProductClickTrackingEnabled()) :
                                    echo $this->helper('WeltPixel\GoogleTagManager\Helper\Data')->addProductClick($_product, $iterator-1);
                                endif; ?>
                                href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                            <div class="product details product-item-details">
                                <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                    href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
                                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                <?php if($elsnerhelper->getAttributeOpetion($_product->getId(),"profession_type")=="B2B"): ?>
                                        <?php if($groupType!="Salon"): ?>
                                            <a class="professional-login links" href="<?= $block->geturl('customer/account/create') ?>">
                                                <span><?= __($ProfessionalText) ?></span>
                                            </a>
                                        <?php else: ?>
                                            <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                            <?= $block->getProductDetailsHtml($_product) ?>
                                        <?php endif; ?>
                                <?php else: ?>
                                    <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                    <?= $block->getProductDetailsHtml($_product) ?>
                                <?php endif; ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                        <div class="professional actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    
                                                    <?php if($elsnerhelper->getAttributeOpetion($_product->getId(),"profession_type")=="B2B"): ?>
                                                        <?php if($groupType!="Salon"): ?>
                                                            <a href="<?= $block->geturl('customer/account/create') ?>" class="professional-searchtext">
                                                                <p class="professional-login"><?= __("Professional Use Only") ?></p>
                                                            </a>
                                                        <?php else: ?>
                                                            <button type="submit"
                                                                title="<?php echo __('Add to cart'); ?>"
                                                                class="action tocart primary"
                                                                disabled>
                                                                <span>
                                                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i><?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                                </span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <button type="submit"
                                                            title="<?php echo __('Add to cart'); ?>"
                                                            class="action tocart primary"
                                                            disabled>
                                                            <span>
                                                        <i class="fa fa-shopping-cart" aria-hidden="true"></i><?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                    </span>
                                                </button>
                                                <?php endif; ?>

                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->isAvailable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <?php if ($showDescription):?>
                                        <div class="product description product-item-description">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                            class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                    <?php elseif($productCountry=="Both" or $productCountry==""): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                        <div class="product-item-info quick-look" data-container="product-grid">
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <a data-wpproductlabel="1" data-product-id="<?php echo $_product->getId() ?>"
                                <?php if ($gtmHelper->isProductClickTrackingEnabled()) :
                                    echo $this->helper('WeltPixel\GoogleTagManager\Helper\Data')->addProductClick($_product, $iterator-1);
                                endif; ?>
                                href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                            <div class="product details product-item-details">
                                <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                    href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
                                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                <?php if($elsnerhelper->getAttributeOpetion($_product->getId(),"profession_type")=="B2B"): ?>
                                        <?php if($groupType!="Salon"): ?>
                                            <a href="<?= $block->geturl('customer/account/create') ?>" >
                                                <p class="professional-login "><?= __("Professional Use Only") ?></p>
                                            </a>
                                        <?php else: ?>
                                            <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                            <?= $block->getProductDetailsHtml($_product) ?>
                                        <?php endif; ?>
                                <?php else: ?>
                                    <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                    <?= $block->getProductDetailsHtml($_product) ?>
                                <?php endif; ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                        <div class="professional actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>

                                                    <?php if($elsnerhelper->getAttributeOpetion($_product->getId(),"profession_type")=="B2B"): ?>
                                                        <?php if($groupType!="Salon"): ?>
                                                            <a href="<?= $block->geturl('customer/account/create') ?>" class="professional-newsearch">
                                                                <p class="professional-login"><?= __("Professional Use Only") ?></p>
                                                            </a>
                                                        <?php else: ?>
                                                            <button type="submit"
                                                                title="<?php echo __('Add to cart'); ?>"
                                                                class="action tocart primary"
                                                                disabled>
                                                                <span>
                                                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i><?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                                </span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                    <button type="submit"
                                                        title="<?php echo __('Add to cart'); ?>"
                                                        class="action tocart primary"
                                                        disabled>
                                                        <span>
                                                            <i class="fa fa-shopping-cart" aria-hidden="true"></i><?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                        </span>
                                                    </button>
                                                    <?php endif; ?>

                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->isAvailable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <?php if ($showDescription):?>
                                        <div class="product description product-item-description">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                            class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                    <?php elseif($currentCountry!=$productCountry): ?>
                        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('no-product')->toHtml(); ?>
                    <?php endif; ?>
            <?php endforeach; ?>
                
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
