<?php
$newCatUrl = $block->getNewcatUrl();
$trendCatUrl = $block->getTrendcatUrl();
$newProducts = $block->getNewProducts(); // New
$trendingProducts = $block->getTrendingProducts(); // Trending
?>
<div class="home-tred-new-section treding_new">
    <div class="home-tred-new-tabes-section btn_viewall_sec">
        <div class="tred-new-tabes trending-new-button">
            <button class="treding-product-tab"><h2><?= /* @noEscape */ __('Trending'); ?></h2></button>
            <button class="new-product-tab"><h2><?= /* @noEscape */ __('New'); ?></h2></button>
        </div>
        <div class="trending_view_all">
            <a href="<?= $escaper->escapeUrl($block->getTrendcatUrl()) ?>" class="trnd-new-url"><?= /* @noEscape */__('View All'); ?></a>
        </div>
    </div>
    <section class="trndprd" id="tranding_block">
        <div class="trend-product-container">    
            <?php foreach ($trendingProducts as $trendingProduct): ?>
                <div class="product_tranding_new_<?php echo $trendingProduct->getId(); ?>">
                    <div class="images_sec">
                        <img src="<?= $block->getProductImageTrending($trendingProduct);?>" alt="<?= $trendingProduct->getName() ?>">
                        <div class="upper_text">
                            <a href="<?= $trendingProduct->getProductUrl(); ?>">
                                <h3><?= $trendingProduct->getName() ?></h3>
                            </a>
                            <div class="price_ comman_tr">
                                <p><?php echo __('Price:'); ?></p>
                                <p><?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($trendingProduct->getPrice(), true, false); ?></p>
                            </div>
                            <div class="star_ comman_tr">
                                <?php $ratingSummary = $block->getRatingSummary($trendingProduct); ?>
	                            <?php if ($ratingSummary): ?>
		                            <div class="rating-summary item" itemprop="reviewRating" itemscope="" >
									    <div class="rating-result" title="<?php echo $ratingSummary; ?>%">
									        <meta itemprop="worstRating" content="1">
									        <meta itemprop="bestRating" content="100">
									        <span style="width:<?php echo $ratingSummary; ?>%">
									            <span itemprop="ratingValue"><?php echo $ratingSummary; ?>%</span>
									        </span>
									        <?php
		                                    $vote = $block->getRating($trendingProduct->getId());
		                                    $totalavg = $vote['count']['avg'];
		                                    ?>
		                                    <div class="rating-summary">
		                                        <span><?= $totalavg ?>/5</span>
		                                    </div>
									    </div>
									</div>
								<?php endif; ?>
                            </div>
                            <div class="cart_btn">
                                <form data-role="tocart-form" action="<?= $block->getAddToCartUrl($trendingProduct) ?>" 
                                    method="post" 
                                    id="product_addtocart_form_trending"> 
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button type="submit" title="<?= __('Add to Cart'); ?>" class="action tocart primary">
                                        <span><?= __('Add to Cart'); ?></span>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <div class="new-product-container" style="display: none;">
            <?php foreach ($newProducts as $newProduct): ?>
                <div class="product_tranding_new_<?php echo $newProduct->getId(); ?>">
                    <div class="images_sec">
                        <img src="<?= $block->getProductImageNew($newProduct);?>" alt="<?= $newProduct->getName() ?>">
                        <div class="upper_text">
                            <a href="<?= $newProduct->getProductUrl(); ?>">
                                <h3><?= $newProduct->getName() ?></h3>
                            </a>
      
                            <div class="price_ comman_tr">
                                <p><?php echo __('Price'); ?></p>
                                <p><?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($newProduct->getPrice(), true, false); ?></p>
                            </div>
                            <div class="star_ comman_tr">
                                <?php $ratingSummary = $block->getRatingSummary($newProduct); ?>
	                            <?php if ($ratingSummary): ?>
		                            <div class="rating-summary item" itemprop="reviewRating" itemscope="" >
									    <div class="rating-result" title="<?php echo $ratingSummary; ?>%">
									        <meta itemprop="worstRating" content="1">
									        <meta itemprop="bestRating" content="100">
									        <span style="width:<?php echo $ratingSummary; ?>%">
									            <span itemprop="ratingValue"><?php echo $ratingSummary; ?>%</span>
									        </span>
									        <?php
		                                    $vote = $block->getRating($newProduct->getId());
		                                    $totalavg = $vote['count']['avg'];
		                                    ?>
		                                    <div class="rating-summary">
		                                        <span><?= $totalavg ?>/5</span>
		                                    </div>
									    </div>
									</div>
								<?php endif; ?>
                            </div>
                            <div class="cart_btn">
                                <form data-role="tocart-form" action="<?= $block->getAddToCartUrl($newProduct) ?>" 
                                    method="post" 
                                    id="product_addtocart_formnew"> 
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button type="submit" title="<?= __('Add to Cart'); ?>" class="action tocart primary">
                                        <span><?= __('Add to Cart'); ?></span>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </section>
</div>
<script type="text/x-magento-init">
{
   ".home-tred-new-section": {
        "Codilar_HelloWorld/js/homeCustomization": {
            "newCatUrl": "<?= $newCatUrl; ?>",
            "trendCatUrl": "<?= $trendCatUrl ?>"
        }
  }
}
</script>
<script type="text/x-magento-init">
    {
        "#product_addtocart_formnew": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form_trending": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
