<?php
   /**
    * Copyright © Magento, Inc. All rights reserved.
    * See COPYING.txt for license details.
    */
   use Magento\Framework\App\Action\Action;
   
   ?>
<?php $viewModel = $block->getData('view_model'); ?>

<?php $helper =  $this->helper("Elsnertech\StorePrice\Helper\NewData"); ?>
<?php $viewModel =  $this->helper("Elsnertech\ProductCustomization\Helper\Data"); ?>
<?php $currentCountry = $viewModel->getCountryName()?>
<?php $groupType = $viewModel->getCurrentCustomeType(); ?>
<?php $ProfessionalText = $viewModel->getProfessionalText(); ?>
<?php 
   if ($currentCountry=="United States") {
       $currentCountry = "US";
   } 
   ?>
<?php
   $_productCollection = $block->getLoadedProductCollection();
   /** @var \Magento\Catalog\Helper\Output $_helper */
   $_helper = $block->getData('outputHelper');
   ?>
<?php if (!$_productCollection->count()): ?>
<div class="message info empty">
   <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
</div>
<?php else: ?>
<?= $block->getToolbarHtml() ?>
<?= $block->getAdditionalHtml() ?>
<?php
   if ($block->getMode() === 'grid') {
       $viewMode = 'grid';
       $imageDisplayArea = 'category_page_grid';
       $showDescription = true;
       $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
   } else {
       $viewMode = 'list';
       $imageDisplayArea = 'category_page_list';
       $showDescription = true;
       $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
   }
   /**
    * Position for actions regarding image size changing in vde if needed
    */
   $pos = $block->getPositioned();
   ?>
<p class="current-country" style="display:none"><?= $currentCountry ?></p>
<div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
   <ol class="products list items product-items">
      <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
      <?php foreach ($_productCollection as $_product): ?>




      <?php $productCountry = $viewModel->getAttributeOpetion($_product->getId(),"country") ?>
      <?php if($currentCountry==$productCountry): ?>
         <li class="item product product-item">
            <div class="product-item-info"
               id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
               data-container="product-<?= /* @noEscape */ $viewMode ?>">
               <?php
                  $productImage = $block->getImage($_product, $imageDisplayArea);
                  if ($pos != null) {
                     $position = 'left:' . $productImage->getWidth() . 'px;'
                        . 'top:' . $productImage->getHeight() . 'px;';
                  }
                  ?>
               <?php // Product Image ?>
               <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                  class="product photo product-item-photo"
                  tabindex="-1">
               <?= $productImage->toHtml() ?>
               </a>
               <div class="product details product-item-details">
                  <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>

                  <strong class="product name product-item-name">
                           <a class="product-item-link"
                              href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                              <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                           </a>
                           <div class="brand-name-featured"><span><?= $_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product); ?></span></div>
                              <span class="ft-dec">
                              <?php if ($showDescription): ?>
                              <div class="product description product-item-description">
                                 <p>
                                    <?= /* @noEscape */ $_helper->productAttribute(
                                       $_product,
                                       $_product->getShortDescription(),
                                       'short_description'
                                       ) ?>
                                 </p>
                              </div>
                              <?php endif; ?>
                           </span>
                        </strong>

                     <?php if($viewModel->getAttributeOpetion($_product->getId(),"profession_type")=="B2B"): ?>
                        <?php if($groupType!="Salon"): ?>
                              <a class="professional-login links" href="<?= $block->geturl('customer/account/create') ?>">
                                 <span><?= __($ProfessionalText) ?></span>
                              </a>
                        <?php else: ?>
                           <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                           <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif; ?>
                     <?php else: ?>
                           <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                           <?= $block->getProductDetailsHtml($_product) ?>
                     <?php endif; ?>
               </div>
               <div class="product-item-inner">
                  <div class="actions-primary">
                     <?php if ($_product->isSaleable()):?>
                     <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                     <form data-role="tocart-form"
                        data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                        action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                        method="post">
                        <input type="hidden"
                           name="product"
                           value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                        <input type="hidden"
                           name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                           value="<?=
                              /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                              ?>">
                        

                        <?php if($viewModel->getAttributeOpetion($_product->getId(),"profession_type")=="B2B"): ?>
                           <?php if($groupType!="Salon"): ?>
                              <a href="<?= $block->geturl('customer/account/create') ?>" class="professional-search">
                                 <p class="professional-login"><?= __("Professional Use Only") ?></p>
                              </a>
                           <?php else: ?>
                              <button type="submit"
                                 title="<?php echo __('Add to cart'); ?>"
                                 class="action tocart primary"
                                 disabled>
                                 <span>
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i><?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                 </span>
                              </button>
                           <?php endif; ?>
                        <?php else: ?>
                           <button type="submit"
                              title="<?php echo __('Add to cart'); ?>"
                              class="action tocart primary"
                              disabled>
                              <span>
                                 <i class="fa fa-shopping-cart" aria-hidden="true"></i><?= $escaper->escapeHtml(__('Add to Cart')) ?>
                              </span>
                           </button>
                        <?php endif; ?>

                     </form>
                     <?php else:?>
                     <?php if ($_product->isAvailable()):?>
                     <div class="stock available">
                        <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                     </div>
                     <?php else:?>
                     <div class="stock unavailable">
                        <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                     </div>
                     <?php endif; ?>
                     <?php endif; ?>
                  </div>
                  <div data-role="add-to-links" class="actions-secondary compare-product">
                     <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                     <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                     <?php endif; ?>
                  </div>
                  <div class="product actions product-item-actions">
                     <?= strpos($pos, $viewMode . '-primary') ?
                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                           $position,
                           'product-item-info_' . $_product->getId() . ' div.actions-primary'
                        ) : '' ?>
                     <?= strpos($pos, $viewMode . '-secondary') ?
                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                           $position,
                           'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                        ) : '' ?>
                  </div>
               </div>
            </div>
            <?= strpos($pos, $viewMode . '-actions') ?
               /* @noEscape */ $secureRenderer->renderStyleAsTag(
                  $position,
                  'product-item-info_' . $_product->getId() . ' div.product-item-actions'
               ) : '' ?>
         </li>
      <?php elseif($productCountry=="Both" or $productCountry==""): ?>
         <li class="item product product-item">
            <div class="product-item-info"
               id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
               data-container="product-<?= /* @noEscape */ $viewMode ?>">
               <?php
                  $productImage = $block->getImage($_product, $imageDisplayArea);
                  if ($pos != null) {
                     $position = 'left:' . $productImage->getWidth() . 'px;'
                        . 'top:' . $productImage->getHeight() . 'px;';
                  }
                  ?>
               <?php // Product Image ?>
               <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                  class="product photo product-item-photo"
                  tabindex="-1">
               <?= $productImage->toHtml() ?>
               </a>
               <div class="product details product-item-details">
                  <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                     <strong class="product name product-item-name">
                           <a class="product-item-link"
                              href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                              <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                           </a>
                           <div class="brand-name-featured"><span><?= $_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product); ?></span></div>
                              <span class="ft-dec">
                              <?php if ($showDescription): ?>
                              <div class="product description product-item-description">
                                 <p>
                                    <?= /* @noEscape */ $_helper->productAttribute(
                                       $_product,
                                       $_product->getShortDescription(),
                                       'short_description'
                                       ) ?>
                                 </p>
                              </div>
                              <?php endif; ?>
                           </span>
                        </strong>
                        <?php if($viewModel->getAttributeOpetion($_product->getId(),"profession_type")=="B2B"): ?>
                           <?php if($groupType!="Salon"): ?>
                                 <a class="professional-login links" href="<?= $block->geturl('customer/account/create') ?>">
                                    <span><?= __($ProfessionalText) ?></span>
                                 </a>
                           <?php else: ?>
                              <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                              <?= $block->getProductDetailsHtml($_product) ?>
                           <?php endif; ?>
                        <?php else: ?>
                           <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                           <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif; ?>
               </div>
               <div class="product-item-inner">
                  <div class="actions-primary">
                     <?php if ($_product->isSaleable()):?>
                     <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                     <form data-role="tocart-form"
                        data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                        action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                        method="post">
                        <input type="hidden"
                           name="product"
                           value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                        <input type="hidden"
                           name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                           value="<?=
                              /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                              ?>">
                        <?= $block->getBlockHtml('formkey') ?>
                        

                        <?php if($viewModel->getAttributeOpetion($_product->getId(),"profession_type")=="B2B"): ?>
                           <?php if($groupType!="Salon"): ?>
                              <a href="<?= $block->geturl('customer/account/create') ?>" class="professional-search">
                                 <p class="professional-login"><?= __("Professional Use Only") ?></p>
                              </a>
                           <?php else: ?>
                              <button type="submit"
                                 title="<?php echo __('Add to cart'); ?>"
                                 class="action tocart primary"
                                 disabled>
                                 <span>
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i><?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                 </span>
                              </button>
                           <?php endif; ?>
                        <?php else: ?>
                           <button type="submit"
                              title="<?php echo __('Add to cart'); ?>"
                              class="action tocart primary"
                              disabled>
                              <span>
                                 <i class="fa fa-shopping-cart" aria-hidden="true"></i><?= $escaper->escapeHtml(__('Add to Cart')) ?>
                              </span>
                           </button>
                        <?php endif; ?>

                     </form>
                     <?php else:?>
                     <?php if ($_product->isAvailable()):?>
                     <div class="stock available">
                        <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                     </div>
                     <?php else:?>
                     <div class="stock unavailable">
                        <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                     </div>
                     <?php endif; ?>
                     <?php endif; ?>
                  </div>
                  <div data-role="add-to-links" class="actions-secondary compare-product">
                     <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                     <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                     <?php endif; ?>
                  </div>
                  <div class="product actions product-item-actions">
                     <?= strpos($pos, $viewMode . '-primary') ?
                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                           $position,
                           'product-item-info_' . $_product->getId() . ' div.actions-primary'
                        ) : '' ?>
                     <?= strpos($pos, $viewMode . '-secondary') ?
                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                           $position,
                           'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                        ) : '' ?>
                  </div>
               </div>
            </div>
            <?= strpos($pos, $viewMode . '-actions') ?
               /* @noEscape */ $secureRenderer->renderStyleAsTag(
                  $position,
                  'product-item-info_' . $_product->getId() . ' div.product-item-actions'
               ) : '' ?>
         </li>
      <?php endif; ?>
      <?php endforeach; ?>
   </ol>
</div>
<?= $block->getToolbarHtml() ?>
<?php if (!$block->isRedirectToCartEnabled()): ?>
<script type="text/x-magento-init">
   {
       "[data-role=tocart-form], .form.map.checkout": {
           "catalogAddToCart": {
               "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
           }
       }
   }
</script>
<?php endif; ?>
<?php endif; ?>