<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$helper = $this->helper('Elsnertech\Customization\Helper\Data');
$CurrentUrl = $helper->getCurrentUrl();
$Baseurl = $helper->getBaseUrl();

$helper_brand = $this->helper('Magiccart\Shopbrand\Helper\Data');
$brandurl = $helper_brand->getRoutes();
$breadcrumbs = $Baseurl."blog";

?>
<?php if ($crumbs && is_array($crumbs)) : ?>

    <?php if (strpos($CurrentUrl, "blog")==true) : ?>
        <div class="wp-beautyroute-breadcrumbs">
    <?php endif; ?>
            <div class="breadcrumbs">
                <ul class="items">
                    <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                        <li class="item <?= $block->escapeHtmlAttr($crumbName) ?>">
                        <?php if ($crumbInfo['link']) : ?>
                            
                            <?php if ($crumbName=="home") : ?>
                                <a href="<?= $Baseurl ?>"
                                title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                                    <?= $block->escapeHtml($crumbInfo['label']) ?>
                                </a>
                            <?php elseif ($crumbName=="brand") : ?>
                                <a href="<?= $Baseurl.$brandurl ?>"
                                title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                                    <?= $block->escapeHtml($crumbInfo['label']) ?>
                                </a>
                            <?php elseif ($crumbName=="blog") : ?>
                                <a href="<?= $block->geturl('blog') ?>"
                                title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                                    <?= $block->escapeHtml($crumbInfo['label']) ?>
                            </a>
                            <?php else : ?>
                                <a href="<?= $block->escapeHtml($crumbInfo['title']) ?>"
                                title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                                    <?= $block->escapeHtml($crumbInfo['label']) ?>
                                </a>
                            <?php endif; ?>

                        <?php elseif ($crumbInfo['last']) : ?>
                            <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                        <?php else : ?>
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>

    <?php if (strpos($CurrentUrl, "blog")==true) : ?>
        </div>
    <?php endif; ?>

<?php endif; ?>
