<?php
$categorycolection = $block->getCategoryCollection();
$mediaUrl = $block->getMediaUrl();
$mediaUrl = str_replace("/media/", "", $mediaUrl);
?>
<div class="featured-caetgory">

    <?php if (count($categorycolection) > 0): ?>
        <div class="heading_sec">
            <h2><?= __('Featured categories'); ?></h2>
        </div>
    <?php endif; ?>

    <?php $i = 0; ?>

    <?php foreach ($categorycolection as $value):
        $distance[] = $value['image_category_order'];
        $colldata[] = $value;
        endforeach;
    ?>

    <?php array_multisort($distance, SORT_ASC, $colldata); ?>

    <div class="products_img">
        <?php foreach ($colldata as $category): ?>

            <?php if ($i==0): ?>
                <div class="inner-custom-div-a">
                    <div class="category-image-custom">
                        <img src="<?= $mediaUrl.$category['mobile_category_image'] ?>" alt=""/>
                        <div class="upper_text_">
                            <h3><?= $category['name'] ?></h3>
                            <a href="<?= $category['url_path'] ?>"><?= __('VIEW ALL COLLECTION'); ?></a>
                        </div>
                    </div>
                </div>

                <div class="inner-custom-div-b">

                    <?php $i=1; ?>
            <?php else: ?>
                    <div class="category-image-custom">
                        <img src="<?= $mediaUrl.$category['mobile_category_image'] ?>" alt=""/>
                        <div class="upper_text_">
                            <h3><?= $category['name'] ?></h3>
                            <a href="<?= $category['url_path'] ?>"><?php echo __('VIEW ALL COLLECTION'); ?></a>
                        </div>
                    </div>
            <?php endif; ?>
        <?php endforeach; ?>
                </div>
    </div>
</div>