<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
$productid = $product->getId();

?>
<div class="prd-wishlist-nam">
<strong class="product-item-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>    
</strong>
<div class="prd-wish-dec">
<span class="prd-dec">
<?php
if (!empty($product->getShortDescription())) {
	

	$sdesc = $product->getShortDescription(); $sdesc = trim($sdesc);
    $limit = 80;
    if (strlen($sdesc) > $limit) {
    $sdesc = substr($sdesc, 0, strrpos(substr($sdesc, 0, $limit), ' '));
    }
    echo $sdesc;
}
?>
</span>
</div>
<div class="prd-sku-size">
<span class="prd-size">
	<?php  echo __('Size');?> <?= $block->escapeHtml($product->getAttributeText('size')); ?>
</span>	
<span class="_devision_">|</span>
<span class="prd-sku">
<?php
 echo __('ITEM');?> <?= $block->escapeHtml($product->getSku()) ?>
</span>
</div>
<div class="prd-color">
       <span><?php echo __('Color:'); ?><?= $block->escapeHtml($product->getAttributeText('color')) ?></span>
</div>
</div>

    	
    	
    	
