<?php /** @var \Magenest\QuickBooksOnline\Block\Adminhtml\Logviewer $block */ ?>

<h3><?= __('Default debug log location: ') . $block->getFileLocation(); ?></h3>
<div style="border: 4px solid #dfdfdf; overflow: hidden; height: 700px; padding: 2px;">
    <div id="log_data" class="qb_log"
         style="width:100%;height:690px;overflow:scroll;margin:0;padding:3px;background:#111111;color:white;
         font:normal 12px Lucida Console, Courier New, serif;">
        <?php /** $block \Magenest\QuickBooksOnline\Block\Adminhtml\Logviewer */ ?>
        <?= /* @noEscape */ $block->getLogContent(); ?>
    </div>
</div>

<style>
    .qb_log {
        overflow-wrap: break-word;
        line-height: 1.0;
    }

    .qb_log pre {
        display: inline;
    }
</style>