<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Wishlist\Block\Link $block */
?>
<li class="link wishlist" data-bind="scope: 'wishlist'">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
        <i class="fa fa-heart" aria-hidden="true"></i>
        <?= $block->escapeHtml($block->getLabel()) ?>
        <!-- ko if: wishlist().counter -->
        <span data-bind="text: wishlist().items.length" class="counter qty"></span>
        <!-- /ko -->
    </a>
</li>


<li class="link wishlist faq" data-bind="scope: 'wishlist'">
    <a href ="<?= /* @noEscape */ $block->geturl('faq') ?>">
        <i class="fa fa-question-circle-o" aria-hidden="true"></i>
        <?= __('FAQs') ?>
    </a>
</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
