<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="social-media">
<?= __('Join The BeautyRoute Mouvement on') ?>
    <img src="/media/wysiwyg/Ftrfacebook.png">
    <img src="/pub/media/wysiwyg/instag.png">
</div>


<div class="comment-form-wrapper">
    <h3 class="heading"><?= __('Leave Us A Comment!') ?></h3>
    
    <form id="respond" method="post" action="<?= $block->escapeUrl($block->getCommentFormAction()) ?>">
        <div class="form-control">
            <label><?= __('Username or Email') ?></label>
            <input feed="text" placeholder="<?= __('Username or Email') ?>" />
        </div>
        <div class="form-control">
            <label>Comment</label>
            <textarea name="comment" placeholder="Write Your Comment here..." rows="4"></textarea>
        </div>

        <button type="submit" name="submit"  class="action submit primary" value="Post your comment" id="post-the-comment">
            <?= __('Leave a comment') ?>
        </button>

        
    </form>
</div>
<script type="text/x-magento-init">{"#respond":{"validation":{}}}</script>