<?php $pcaSettings = $this->helper('PCAPredict\Tag\Helper\SettingsData'); $pcaAccCode = $pcaSettings->getAccountCode(); $pcaCustomJSBack = $pcaSettings->getCustomJavaScriptBack(); if ($pcaAccCode) { ?> <script>

    (function (a, c, b, e) {
    a[b] = a[b] || {}; a[b].initial = { accountCode: "<?php echo $pcaAccCode; ?>", host: "<?php echo $pcaAccCode; ?>.pcapredict.com" };
    a[b].on = a[b].on || function () { (a[b].onq = a[b].onq || []).push(arguments) }; var d = c.createElement("script");
    d.async = !0; d.src = e; c = c.getElementsByTagName("script")[0]; c.parentNode.insertBefore(d, c)
    })(window, document, "pca", "/" + "/<?php echo $pcaAccCode; ?>.pcapredict.com/js/sensor.js");

    requirejs(['jquery', 'Magento_Sales/order/create/form'], function(){

        (function() {

            pca.magento = pca.magento || {};

            pca.magento.isElementVisible = function( elem ) {
                if (elem) {
                    return !!( elem.offsetWidth || elem.offsetHeight || elem.getClientRects().length );
                }
                return false;
            };

            var fieldsToPopulate = [];

            pca.on('data', function(source, key, address, variations) {
                
                
                
                
                
                
                var fieldsToFire = pca.platform.productList[key]["PLATFORM_CAPTUREPLUS"].bindings[0].fields;
                
                for (var i = 0; i < fieldsToFire.length; i++) {
                    
                    var ele = document.getElementById(fieldsToFire[i].element);

                    if (ele !== undefined || ele != null) {
                        fieldsToPopulate.push({
                            id : ele.id,
                            value : ele.value
                        });
                    }
                }
                
                var ele = document.getElementById(fieldsToFire[0].element);

                if (ele !== undefined || ele != null) {
                    pca.fire(ele, 'change');
                }
            });

            pca.magento.anyBindingsVisible = function(bindingList){

                for (var i = 0; i < bindingList.length; i++) {
                    var fieldSet = bindingList[i].fields;

                    var res = fieldSet.filter(function (x) { return pca.magento.isElementVisible(document.getElementById(x.element)); });

                    if (res.length > 0){
                        return true;
                    }
                }

                return false;
            }

            pca.magento.loadPca = function() {

                
                
                

                var curr = order.loadArea;
                order.loadArea = function(area, indicator, params) {
                    
                    var prom = curr.apply(this, arguments);
                    
                    prom.then(function() {
                        
                        if (fieldsToPopulate.length > 0){
                            for (var i = 0; i < fieldsToPopulate.length; i++) {
                                document.getElementById(fieldsToPopulate[i].id).value = fieldsToPopulate[i].value;
                            }
                        }
                        
                        if (document.getElementById("order-shipping_same_as_billing").checked == true) {
                            for (var i = 0; i < fieldsToPopulate.length; i++) {

                                var ship = fieldsToPopulate[i].id.replace("billing", "shipping");

                                document.getElementById(ship).value = fieldsToPopulate[i].value;
                            }
                        }
                        
                        fieldsToPopulate = [];

                        pca.load();
                    })
                }

                pca.load();
            }
            
            pca.magento.doLoad = function() {
                
                if (pca
                    && pca.platform
                    && typeof pca.platform.elementExists === 'function'
                    && pca.platform.getBindingsForService("PLATFORM_CAPTUREPLUS")
                    && pca.magento.anyBindingsVisible(pca.platform.getBindingsForService("PLATFORM_CAPTUREPLUS"))){
                    
                    pca.magento.loadPca();
                }
                else 
                {
                    
                    window.setTimeout(pca.magento.doLoad, 500);
                }
            }

            <?php if ($pcaCustomJSBack) echo $pcaCustomJSBack; ?>   

            
            pca.magento.doLoad();
            
        })();
    });</script><?php }