<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();   
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');    
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
$getStorecode= $storeManager->getStore()->getCode();
?>
<?php $url= "https://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
?>
<?php
    if (strpos($url, '/en/') !== false) 
    {
        ?>
        <?php

        // echo "Test"; die();
        $validURL = str_replace("/en/", "/", $url); 
        header('Location: '.$validURL);   
        exit();
    }
?>
