<?php
/**
 *
 * @var $block \Magento\Framework\View\Element\Template
 * 
 */
?>
<?php
$helper = $this->helper('Magiccart\Shopbrand\Helper\Data');
$params = $this->getRequest()->getParams();
?>
<div class="brand-title-">
    <h3><?php echo __('select any brand to proceed') ?></h3>

</div>
<div class="characters">
    <ul class="filter">
        <?php if (isset($params['keyword']) && $params['keyword'] != ''): ?>
          <li class="char <?php if (isset($params['char']) && $params['char'] == '0-9'): ?>active<?php endif; ?>"><a title="<?php echo __('0-9'); ?>" href="<?php echo $helper->getBrandUrl('?keyword=0-9', false); ?>"><?php echo __('0-9'); ?></a></li>
            <?php foreach (range('a', 'z') as $char): ?>
                <li class=char "<?php if (isset($params['char']) && $params['char'] == $char): ?>active<?php endif; ?>"><a href="<?php echo $helper->getBrandUrl("?keyword=$char", false); ?>"><?php echo $char; ?></a></li>
            <?php endforeach; ?>
        <?php else: ?>
            <li class=char "<?php if (isset($params['char']) && $params['char'] == '0-9'): ?>active<?php endif; ?>"><a title="<?php echo __('0-9'); ?>" href="<?php echo $helper->getBrandUrl('?keyword=0-9') ; ?>"><?php echo __('0-9'); ?></a></li>
            <?php foreach (range('a', 'z') as $char): ?>
                <li class="char <?php if (isset($params['char']) && $params['char'] == $char): ?>active<?php endif; ?>"><a href="<?php echo $helper->getBrandUrl("?keyword=$char", false); ?>"><?php echo $char; ?></a></li>
            <?php endforeach; ?>
        <?php endif; ?>
     </div>
    </ul>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){$(document).ready( function() {$('.char').click(function(){$(this).addClass('active');});});});
</script>