<?php $items = $block->getCancleOrder() ?>
<?php foreach ($items as $item): ?>
    <tr class="q">
  <td align="center" class="u" style="padding:0;height:100px;word-wrap:break-word;vertical-align:top;" width="34.083333333333336%">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <td align="center" class="i fwm" width="100%">
          <img src='<?= $block->getProductImage($item->getProductId())?>' style="display:block;width:197px;height:100px;" width="197" />
        </td>
      </tr>
    </table>
  </td>
  <td class="tgtr" style="vertical-align:top;color:transparent;font-size:0;" width="0.6666666666666666%"></td>
  <td align="left" class="u" style="padding:8px 8px 8px 8px;height:91px;word-wrap:break-word;vertical-align:top;" width="34.083333333333336%">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <td align="left" class="x tm" style="padding-bottom:4px;" width="100%">
          <p style="Margin:0;text-align:left;">
            <span style="font-size:14px;font-family:Inter,Arial,sans-serif;font-weight:700;color:#000000;line-height:18px;"><?= $item->getName() ?></span>
          </p>
        </td>
      </tr>
      <tr>
        <td align="left" class="x" width="100%">
          <p style="Margin:0;text-align:left;">
            <span style="font-size:13px;font-family:Inter,Arial,sans-serif;font-weight:400;color:#000000;line-height:17px;">Qty: <?= $item->getQtyOrdered() ?></span>
          </p>
        </td>
      </tr>
    </table>
  </td>
  <td class="tgtr" style="vertical-align:top;color:transparent;font-size:0;" width="0.6666666666666666%"></td>
  <td align="center" class="u" style="height:33px;word-wrap:break-word;vertical-align:middle;" width="15%">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <td align="center" class="x" width="100%">
          <p style="Margin:0;text-align:center;">
            <span style="font-size:14px;font-family:Inter,Arial,sans-serif;font-weight:400;color:#000000;line-height:17px;">$<?= $item->getbaseRowTotal() ?></span>
          </p>
        </td>
      </tr>
    </table>
  </td>
</tr>
<tr class="">
  <td class="s" style="font-size:0;padding:0;padding-bottom:0;word-break:break-word;color:transparent;">
    <div style="height:8px;line-height:8px;"></div>
  </td>
</tr>
<?php endforeach; ?>