<?php
/**
 * Copyright © 2017 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="connection_success" align="center">
    <span style="color: red; font-size: 18pt" ><?= __("You are connected!"); ?></span>
    <br>
    <span><?= __("Please wait"); ?></span>
</div>

<script type="text/javascript">
    window.opener.location.reload(false);
    window.setTimeout('window.close()', 4000);
</script>